/*Login - Create Account*/
USE QLBAN_THUENHA
GO

/*Hàm generate mã nv tự động*/
IF OBJECT_ID('GENERATE_MANV') IS NOT NULL
	DROP FUNCTION dbo.GENERATE_MANV
GO
CREATE FUNCTION GENERATE_MANV ()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MANV CHAR(5);
	DECLARE @INDEX INT = 2;
	SET @MANV = 'NV001';
	WHILE(EXISTS (SELECT NHANVIEN.MA_NV FROM NHANVIEN WHERE NHANVIEN.MA_NV = @MANV)) --Lay MANHA co trong NHA + 1
		BEGIN
			IF (@INDEX < 10)
			BEGIN
				SET @MANV = 'NV00' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10 AND @INDEX < 100)
			BEGIN
				SET @MANV = 'NV0' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 100 AND @INDEX < 1000)
			BEGIN
				SET @MANV = 'NV' + CONVERT(CHAR(5),@INDEX)
			END
			SET @INDEX = @INDEX + 1
		END
	RETURN @MANV
END
GO

/*Hàm generate mã khách hàng tự động*/
IF OBJECT_ID('GENERATE_MAKH') IS NOT NULL
	DROP FUNCTION dbo.GENERATE_MAKH
GO
CREATE FUNCTION GENERATE_MAKH ()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MAKH CHAR(5);
	DECLARE @INDEX INT = 2;
	SET @MAKH = 'KH001';
	WHILE(EXISTS (SELECT KHACHHANG.MA_KH FROM KHACHHANG WHERE KHACHHANG.MA_KH = @MAKH)) 
		BEGIN
			IF (@INDEX < 10)
			BEGIN
				SET @MAKH = 'KH00' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10 AND @INDEX < 100)
			BEGIN
				SET @MAKH = 'KH0' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 100 AND @INDEX < 1000)
			BEGIN
				SET @MAKH = 'KH' + CONVERT(CHAR(5),@INDEX)
			END
			SET @INDEX = @INDEX + 1
		END
	RETURN @MAKH
END
GO

/*Hàm generate mã chủ nhà tự động*/
IF OBJECT_ID('GENERATE_MACHUNHA') IS NOT NULL
	DROP FUNCTION dbo.GENERATE_MACHUNHA
GO

CREATE FUNCTION GENERATE_MACHUNHA ()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MACN CHAR(5);
	DECLARE @INDEX INT = 2;
	SET @MACN = 'CN001';
	WHILE(EXISTS (SELECT CHUNHA.MA_CNHA FROM CHUNHA WHERE CHUNHA.MA_CNHA = @MACN)) 
		BEGIN
			IF (@INDEX < 10)
			BEGIN
				SET @MACN = 'CN00' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10 AND @INDEX < 100)
			BEGIN
				SET @MACN = 'CN0' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 100 AND @INDEX < 1000)
			BEGIN
				SET @MACN = 'CN' + CONVERT(CHAR(5),@INDEX)
			END
			SET @INDEX = @INDEX + 1
		END
	RETURN @MACN
END
GO

/*Hàm kiểm tra kết quả đăng nhập*/
/*Về phía chủ nhà*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('USP_LOGIN_CN','P') IS NOT NULL
	DROP PROC USP_LOGIN_CN
GO
CREATE PROC USP_LOGIN_CN
@USERNAME VARCHAR(50), 
@PASS VARCHAR(50),
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(500) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM CHUNHA WHERE CHUNHA.USER_CNHA = @USERNAME)
		BEGIN
			PRINT N'Username không tồn tại';
			set @RETURNCODE = 1;
			set @RETURNMESS = N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM CHUNHA WHERE CHUNHA.USER_CNHA = @USERNAME AND CHUNHA.PASS_CNHA = @PASS)
		BEGIN
			set @RETURNCODE = 1
			set @RETURNMESS = N'Sai mật khẩu';
			PRINT N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		set @RETURNCODE = 1
		set @RETURNMESS = N'Lỗi đăng nhập';
		PRINT N'Lỗi đăng nhập';
		ROLLBACK TRANSACTION;
	END CATCH
	set @RETURNCODE = 0
	set @RETURNMESS = N'Đăng nhập thành công';
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION

--DECLARE @CODE INT, @MESS NVARCHAR(500)
--EXEC USP_LOGIN_CN 'hnglinh232','hnglinh',@RETURNCODE = @CODE, @RETURNMESS = @MESS

/*Về phía KH*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('USP_LOGIN_KH_QLNHA','P') IS NOT NULL
	DROP PROC USP_LOGIN_KH_QLNHA
GO

CREATE PROC USP_LOGIN_KH_QLNHA
@USERNAME VARCHAR(50), 
@PASS VARCHAR(50),
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(100) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USER_KH = @USERNAME)
		BEGIN
			PRINT N'Username không tồn tại';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USER_KH = @USERNAME AND KHACHHANG.PASS_KH = @PASS)
		BEGIN
			PRINT N'Sai mật khẩu';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi đăng nhập';
		SET @RETURNCODE = 1;
		SET @RETURNMESS = N'Lỗi đăng nhập';
		ROLLBACK TRANSACTION;
	END CATCH
	SET @RETURNCODE = 0;
	SET @RETURNMESS = N'Đăng nhập thành công'
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION

--DECLARE @CODE INT, @MESS NVARCHAR(500)
--EXEC USP_LOGIN_KH_QLNHA 'hnglinh232','hnglinh',@RETURNCODE = @CODE, @RETURNMESS = @MESS

/*Ve phia NV*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('USP_LOGIN_NHANVIEN','P') IS NOT NULL
	DROP PROC USP_LOGIN_NHANVIEN
GO

CREATE PROC USP_LOGIN_NHANVIEN
@USERNAME VARCHAR(50), 
@PASS VARCHAR(50),
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(100) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE NHANVIEN.USER_NV = @USERNAME)
		BEGIN
			PRINT N'Username không tồn tại';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE NHANVIEN.USER_NV = @USERNAME AND NHANVIEN.PASS_NV = @PASS)
		BEGIN
			PRINT N'Sai mật khẩu';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi đăng nhập'
		SET @RETURNCODE = 1;
		SET @RETURNMESS = N'Lỗi đăng nhập'
		ROLLBACK TRANSACTION;
	END CATCH
	SET @RETURNCODE = 0;
	SET @RETURNMESS = N'Đăng nhập thành công'
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION

--DECLARE @CODE INT, @MESS NVARCHAR(500)
--EXEC USP_LOGIN_NHANVIEN 'lamchikhanh','123456789',@RETURNCODE = @CODE, @RETURNMESS = @MESS


/*-------------TAO TAI KHOAN------------*/
/*KH*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('CREATE_ACCOUNT_QLNHA_KH','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_QLNHA_KH
GO

CREATE PROC CREATE_ACCOUNT_QLNHA_KH
@USERNAME VARCHAR(50),
@PASS VARCHAR(50),
@TEN NVARCHAR(50),
@SDT VARCHAR(15),
@TIEUCHIKH NVARCHAR(100) = NULL,
@DCHIKH NVARCHAR(250) = NULL,
@CHINHANHTHUOCVE CHAR(5) = 'CI001',
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(100) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT * FROM NHANVIEN WHERE NHANVIEN.USER_NV = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF(EXISTS (SELECT * FROM CHUNHA WHERE CHUNHA.USER_CNHA = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM CHINHANH WHERE CHINHANH.MA_CN = @CHINHANHTHUOCVE)
		BEGIN
			PRINT N'Ma CN khong ton tai';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Ma CN khong ton tai';
			ROLLBACK TRANSACTION;
			RETURN;
		END
			DECLARE @KHACHHANGID CHAR(5);
			SET @KHACHHANGID = (SELECT dbo.GENERATE_MAKH() AS MAKHMOI);
			INSERT INTO KHACHHANG
			VALUES(@KHACHHANGID, @TEN, @SDT, @TIEUCHIKH, @DCHIKH ,@USERNAME, @PASS, @CHINHANHTHUOCVE)
	END TRY
	BEGIN CATCH
		PRINT N'Tạo tk thất bại'
		SET @RETURNCODE = 1;
		SET @RETURNMESS = N'Tạo tk thất bại';
		ROLLBACK TRANSACTION;
	END CATCH
	PRINT N'Tạo tk cho KH thành công';
	SELECT ERROR_MESSAGE() AS ErrorMessage;  
	SET @RETURNCODE = 0;
	SET @RETURNMESS = N'Tạo tk cho KH thành công';
COMMIT TRANSACTION

--DECLARE @CODE INT, @MESS NVARCHAR(100)
--EXEC CREATE_ACCOUNT_QLNHA_KH 'vegeta','111222',N'Linh Trúc','09012345678',N'Tìm nhà thuê',N'KTX Trần Hưng Đạo','CI002',@CODE, @MESS

/*NBH*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('CREATE_ACCOUNT_QLNHA_CHUNHA','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_QLNHA_CHUNHA
GO

CREATE PROC CREATE_ACCOUNT_QLNHA_CHUNHA
@USERNAME VARCHAR(50),
@PASS VARCHAR(50),
@TEN NVARCHAR(50),
@SDT VARCHAR(15),
@DCHICHUNHA NVARCHAR(250) = NULL,
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(100) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT * FROM NHANVIEN WHERE NHANVIEN.USER_NV = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF(EXISTS (SELECT * FROM KHACHHANG AS KH WHERE KH.USER_KH = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
			DECLARE @CHUNHAID CHAR(5);
			SET @CHUNHAID = (SELECT dbo.GENERATE_MACHUNHA() AS MANHADUOCTAO);
			INSERT INTO CHUNHA
			VALUES(@CHUNHAID, @TEN, @DCHICHUNHA, @SDT, @USERNAME, @PASS)
	END TRY
	BEGIN CATCH
		PRINT N'Tạo tk thất bại'
		SET @RETURNCODE = 1;
		SET @RETURNMESS = N'Tạo tk thất bại';
		--SELECT ERROR_MESSAGE() AS ErrorMessage;    
		ROLLBACK TRANSACTION;
		RETURN;
	END CATCH
	PRINT N'Tạo tk cho CHU NHA thành công';
	SET @RETURNCODE = 0;
	SET @RETURNMESS = N'Tạo tk cho CHU NHA thành công';
COMMIT TRANSACTION


SELECT * FROM CHUNHA
DECLARE @CODE INT, @MESS NVARCHAR(100)
EXEC CREATE_ACCOUNT_QLNHA_CHUNHA 'ahihi','111222',N'Linh Trúc','09012345678',N'KTX Trần Hưng Đạo',@CODE, @MESS


/*NV*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('CREATE_ACCOUNT_QLNHA_NV','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_QLNHA_NV
GO

CREATE PROC CREATE_ACCOUNT_QLNHA_NV
@USERNAME VARCHAR(50),
@PASS VARCHAR(50),
@TEN NVARCHAR(50),
@SDT VARCHAR(15),
@DCHINV NVARCHAR(250) = NULL,
@NGAYSINH DATE = '2000-01-01',
@CNLAMVIEC CHAR(5) = 'CI001',
@CNQUANLY CHAR(5) = NULL,
@RETURNCODE INT OUTPUT,
@RETURNMESS NVARCHAR(100) OUTPUT
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT * FROM CHUNHA WHERE CHUNHA.USER_CNHA = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF(EXISTS (SELECT * FROM KHACHHANG AS KH WHERE KH.USER_KH = @USERNAME))
		BEGIN
			PRINT N'Username này đã có rồi';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Username này đã có rồi';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM CHINHANH WHERE CHINHANH.MA_CN = @CNLAMVIEC)
		BEGIN
			PRINT N'Ma CN khong ton tai';
			SET @RETURNCODE = 1;
			SET @RETURNMESS = N'Ma CN khong ton tai';
			ROLLBACK TRANSACTION;
			RETURN;
		END
			DECLARE @NHANVIENID CHAR(5);
			SET @NHANVIENID = (SELECT dbo.GENERATE_MANV() AS MANVMOI);
			INSERT INTO NHANVIEN
			VALUES(@NHANVIENID, @TEN, @SDT, @DCHINV, @NGAYSINH, 100000 ,@USERNAME, @PASS, @CNLAMVIEC)
		/*Nếu là nhân viên quản lý --> điền vào trường chi nhánh quản lý*/
		IF(@CNQUANLY IS NOT NULL)
		BEGIN
			IF NOT EXISTS (SELECT * FROM CHINHANH WHERE CHINHANH.MA_CN = @CNQUANLY)
				BEGIN
					PRINT N'Ma CN khong ton tai';
					SET @RETURNCODE = 1;
					SET @RETURNMESS = N'Ma CN khong ton tai';
					ROLLBACK TRANSACTION;
					RETURN;
				END
			UPDATE CHINHANH
			SET CHINHANH.NVQUANLY = @NHANVIENID
			WHERE CHINHANH.MA_CN = @CNQUANLY
		END
	END TRY
	BEGIN CATCH
		PRINT N'Tạo tk thất bại';
		SELECT ERROR_MESSAGE() AS ErrorMessage;  
		SET @RETURNCODE = 1;
		SET @RETURNMESS = N'Tạo tk thất bại';
		ROLLBACK TRANSACTION;
		RETURN;
	END CATCH
	PRINT N'Tạo tk cho NV thành công';
	SET @RETURNCODE = 0;
	SET @RETURNMESS = N'Tạo tk cho NV thành công';
COMMIT TRANSACTION

DECLARE @CODE INT, @MESS NVARCHAR(100)

SELECT * FROM CHUNHA
SELECT * FROM NHANVIEN
SELECT * FROM KHACHHANG

SELECT * FROM NHA, NHABAN WHERE NHABAN.MA_NHA = NHA.MA_NHA

SELECT * FROM NHA, NHABAN WHERE NHA.MA_NHA = NHABAN.MA_NHA
EXEC CREATE_ACCOUNT_QLNHA_NV 'hoalienthienquan','26102000',N'Hoa Liên','0901234567',N'KTX trường ĐH Kinh tế', '2000-10-10','CI001','CI003', @RETURNCODE = @CODE, @RETURNMESS = @MESS