-- nhà bán
use QLBAN_THUENHA
go

DECLARE @CODE INT, @MESS NVARCHAR(100)
EXEC chinhsua_loainha_ban_FIX_DIRTY @MANHA = 'N0001', @MA_LN = NULL, @TINHTRANG = NULL,
	@GIABAN = 20000001, @KHUVUC = NULL, @DUONG =NULL, @QUAN = NULL,
	@TPHO = NULL, @NHH = NULL, @SLP = NULL, @CHINHANH = NULL, @RETURNCODE = @CODE, @RETURNMESS = @MESS
go

select * from nhaban